apiVersion: mesh.cellery.io/v1alpha2
kind: Composite
metadata:
  name: stock-options
  annotations:
    mesh.cellery.io/cell-image-org: cellery-samples
    mesh.cellery.io/cell-image-name: stock-options
    mesh.cellery.io/cell-image-version: 1.0.0
spec:
  components:
  - metadata:
      name: stock
    spec:
      scalingPolicy:
        replicas: 1
      template:
        containers:
        - image: docker.io/celleryio/sampleapp-stock
          name: stock
      ports:
      - port: 80
        protocol: HTTP
        targetPort: 8080
  - metadata:
      name: debug
    spec:
      scalingPolicy:
        replicas: 1
      template:
        containers:
        - name: debug
          image: docker.io/mirage20/k8s-debug-tools

