apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cellery-system-webhook-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook
  namespace: cellery-system

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cellery-system-webhook-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cellery-system-webhook-role
subjects:
  - kind: ServiceAccount
    name: webhook
    namespace: cellery-system

---
apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: cellery-system
spec:
  selector:
    app: webhook
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: cellery-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: webhook
    spec:
      containers:
        - name: webhook
          image: wso2cellery/mesh-webhook:latest
      serviceAccountName: webhook
